### ISSUE TITLE
UpperCase in meta fields on pageTranslation entity

### ISSUE THREAD

**Issue by rzp-789** [monsieurbiz/SyliusCmsPagePlugin#37]
Problems on Admin in index page with the render of template @SyliusAdmin\Crud/index.html.twig because metaTitle, metaKeywords, metaDescription are mapping with an underscore (meta_title, .... ) Solution is to rename the fields with underscore

```
<?php

declare(strict_types=1);

namespace App\Entity;

use MonsieurBiz\SyliusCmsPagePlugin\Entity\PageTranslation as BasePageTranslation;
use Doctrine\ORM\Mapping as ORM;

class PageTranslation extends BasePageTranslation
{

    /**
     * @ORM\Column(name="meta_title")
     */
    protected $metaTitle;

    /**
     * ORM\Column(name="meta_keywords")
     */
    protected $metaKeywords;

    /**
     * ORM\Column(name="meta_description")
     */
    protected $metaDescription;


}
```

**Comment by jacquesbh** [comment]
I feel that this issue doesn't longer exist. The mapping is done in `src/Resources/config/doctrine/PageTranslation.orm.xml`.

**Comment by maximehuran** [comment]
It still exists

<img width="934" alt="image" src="https://github.com/monsieurbiz/SyliusCmsPagePlugin/assets/11380627/f8f2185e-7179-4834-9422-a97b073812f4">
