### ISSUE TITLE
Does this bundle really need to depend on sylius/sylius?

### ISSUE THREAD

**Issue by welcoMattic** [monsieurbiz/SyliusCmsPagePlugin#51]
I'm trying to install this bundle in a Monofony application. It fails because Monofony does not provider SyliusPluginTrait (as Monofony not depends on sylius/SyliusCoreBundle).

If SyliusCmsPagePlugin could directly depends on sylius/SyliusCoreBundle (and some other Sylius bundles if needed) instead of sylius/sylius, I guess it could allow the installation on Monofony.

cc @maximehuran @jacquesbh

**Comment by maximehuran** [comment]
We do not provide Monofony compatibility and still working with Sylius and [NoCommerce](https://github.com/monsieurbiz/SyliusNoCommercePlugin)
