### ISSUE TITLE
RC14 OK - 1.0.0 KO

### ISSUE THREAD

**Issue by agencealaska** [monsieurbiz/SyliusCmsPagePlugin#57]
Hi

since upgrade from RC14 to 1.0.0 we have this issue : 

`Unable to find template "@SyliusAdmin/Grid/Field/_channels.html.twig" (looked into: /var/www/html/templates/bundles/SyliusAdminBundle, /var/www/html/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/views).
`

any idea ?

**Comment by maximehuran** [comment]
Hi @agencealaska

Which version of Sylius are you using ? 
Did you check if you have a file somewhere in your vendor called `/Field/_channels.html.twig` ?

For example with VSCode : 

![image](https://github.com/monsieurbiz/SyliusCmsPagePlugin/assets/11380627/e3377c21-f233-4afa-bf8f-5cb4c5434fe0)

**Comment by maximehuran** [comment]
I will let you reopen the issue if needed

**Comment by bellu** [comment]
I had the same problem, i'm using sylius 1.10.9. 
I fixed it restoring this file [https://github.com/Sylius/Sylius/tree/1.14/src/Sylius/Bundle/AdminBundle/Resources/views/Grid/Field](url)

**Comment by maximehuran** [comment]
We advise you to update your platform to Sylius 1.13. For further information, please have a look to the compatible versions of the current plugin : https://github.com/monsieurbiz/SyliusCmsPagePlugin?tab=readme-ov-file#compatibility
